from mididings import *

config(
    backend='jack-rt',
    client_name='tr6s_multiplexer'
)

run(
    scenes = {
        1: Scene("Channel 1",
            Channel(1),
        ),
        2: Scene("Channel 2",
            Channel(2),
        ),
        3: Scene("Channel 3",
            Channel(3),
        ),
        4: Scene("Channel 4",
            Channel(4),
        ),
        5: Scene("Channel 5",
            Channel(5),
        ),
        6: Scene("Channel 6",
            Channel(6),
        ),
        7: Scene("Channel 7",
            Channel(7),
        ),
        8: Scene("Channel 8",
            Channel(8),
        ),
        9: Scene("Channel 9",
            Channel(9),
        ),
        10: Scene("Channel 10",
            Channel(10),
        ),
        11: Scene("Channel 11",
            Channel(11),
        ),
        12: Scene("Channel 12",
            Channel(12),
        ),
        13: Scene("Channel 13",
            Channel(13),
        ),
        14: Scene("Channel 14",
            Channel(14),
        ),
        15: Scene("Channel 15",
            Channel(15),
        ),
        16: Scene("Channel 16",
            Channel(16),
        ),
    },
    control = ChannelFilter(10) >> SceneSwitch(),
#    pre = ~ChannelFilter(PROGRAM),
)
